ALTER TABLE `Post` DROP FOREIGN KEY `Post_userId_fkey`;
ALTER TABLE `Comment` DROP FOREIGN KEY `Comment_userId_fkey`;

ALTER TABLE `Post` MODIFY `userId` INTEGER NULL;
ALTER TABLE `Comment` MODIFY `userId` INTEGER NULL;

ALTER TABLE `Post` ADD CONSTRAINT `Post_userId_fkey`
  FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `Comment` ADD CONSTRAINT `Comment_userId_fkey`
  FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
